codecov:
  require_ci_to_pass: false

coverage:
  precision: 2
  round: up
  range: "70...90"
  status:
    project:
      default:
        target: auto
        threshold: 15%
        base: auto
    patch:
      default:
        target: 0%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/**"
  - "test_*.py"
  - "h2p_parser/utils/**"
  - "h2p_parser/data/**"
  - "**/__main__.py"
  - "**/__init__.py"
